//
//  BucketListPresenter.swift
//  CleanSwiftExample
//
//  Created by 최승환 on 2019. 3. 9..
//  Copyright (c) 2019년 최승환. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BucketListPresentationLogic
{
  func presentBucketList(response: BucketList.Something.Response)
}

class BucketListPresenter: BucketListPresentationLogic
{
  weak var viewController: BucketListDisplayLogic?
  
  // MARK: Do something
  
  func presentBucketList(response: BucketList.Something.Response)
  {
    
    var dataList: [BucketList.Something.ViewModel.ViewModelMenu] = []
    var totalPrice = 0
    
    for i in response.selectedMenuList {
        let data = BucketList.Something.ViewModel.ViewModelMenu(name: i.name, price: "₩ \(i.price)")
        dataList.append(data)
        totalPrice += i.price
    }
    let viewModel = BucketList.Something.ViewModel(bucketList: dataList)
    viewController?.displayBucketList(viewModel: viewModel, totalPrice: totalPrice)
  }
}
