//
//  MenuListPresenter.swift
//  CleanSwiftExample
//
//  Created by 최승환 on 2019. 3. 9..
//  Copyright (c) 2019년 최승환. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MenuListPresentationLogic
{
  func presentMenuList(response: MenuList.Something.Response)
}

class MenuListPresenter: MenuListPresentationLogic
{
  weak var viewController: MenuListDisplayLogic?
  
  // MARK: Do something
  
  func presentMenuList(response: MenuList.Something.Response)
  {
    
    var dataList: [MenuList.Something.ViewModel.ViewModelMenu] = []
    for i in response.menuList {
        let data = MenuList.Something.ViewModel.ViewModelMenu(name: i.name, price: "₩ \(i.price)")
        dataList.append(data)
    }
    
    let viewModel = MenuList.Something.ViewModel(menuList: dataList)
    viewController?.displayMenu(viewModel: viewModel)
  }
}
